server:
  port: 8081
  servlet:
    context-path: /api  #上下文路径

spring:
  datasource:
    url: jdbc:mysql://119.23.248.220:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: jonlin
    password: jonlin@666
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


# redis key前缀
redis-key-prefix: jonlin:test