package com.jonlin.mapper;

import com.jonlin.entity.TransLadingBill;
import java.util.List;

public interface TransLadingBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_lading_bill
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_lading_bill
     *
     * @mbggenerated
     */
    int insert(TransLadingBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_lading_bill
     *
     * @mbggenerated
     */
    TransLadingBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_lading_bill
     *
     * @mbggenerated
     */
    List<TransLadingBill> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_lading_bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TransLadingBill record);
}